
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    password: 'root'
    username: 'root'
  jpa:
    hibernate:
      # ddl-auto: 'none'
      ddl-auto: 'update'
      open-in-view: 'false'
      show-sql: 'true'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        format_sql: 'true'
      jdbc:
        time_zone: 'UTC'

server:
  port: 8086
logger:
  org:
    hibernate:
      dialect:
        function:
          TemplateRenderer:
            level: 'ERR'
flicker:
  apiKey: 'c2245a206e38b86664249bfd2a5034ca'
  apiSecret: '004fa61215b7a40e'
  appKey: '72157720874338642-39d2d25b04cd899e'
  appSecret: 'f054f7000dde440a'